[project]
name = "ansible-role-base"
version = "0.1.0"
description = "Ansible Role for Base Configuration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.1.0",
    "ansible-lint>=6.8.7",
    "molecule>=24.12.0",
    "molecule-docker>=2.1.0",
]
