---
- name: Make sure sshd is installed
  ansible.builtin.package:
    name: openssh-server
    state: present

- name: "Set SSH Config Options"
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
    backup: yes
  notify: Restart sshd
  loop: "{{ lockdown_ssh_config_default | combine(lockdown_ssh_config_default) | dict2items }}"

- name: "Set sudoers ssh key forward to: {{ lockdown_ssh_allow_agent_forward_sudo }}"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers.d/ssh_key_forward
    line: "Defaults env_keep += SSH_AUTH_SOCK"
    state: "{{ 'present' if lockdown_ssh_allow_agent_forward_sudo else 'absent' }}"
    backup: yes
    validate: "visudo -cf %s"
    mode: 0440
    create: yes
  notify: Restart sshd
  tags: ["skip_ansible_lint"] # because of state template

- name: Set Known_Hosts
  become: yes
  ansible.builtin.blockinfile:
    path: "{{ item.dest }}"
    block: "{{ lockdown_ssh_known_hosts }}"
    marker: "<!-- {mark} ANSIBLE MANAGED SSH lockdown_ssh_known_hosts -->"
    create: yes
    owner: "{{ item.owner }}"
    mode: 0600
  loop:
    - dest: /root/.ssh/known_hosts
      owner: root
    - dest: "{{ ansible_env.HOME }}/.ssh/known_hosts"
      owner: "{{ ansible_user_id }}"
